### PR TITLE
Several Windows fixes.

### LINKED ISSUE #22: Executing a file with a relative path on Windows is broken
If I pass in a relative path on Windows to execute (assuming what I want to execute is already in the working directory or in my PATH environment variable), it produces incorrect output.

For example:

    mysqldump --defaults-extra-file=C:\temp\my.cnf --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --set-charset --triggers --result-file=C:\temp\backup.sql testdatabase

Will produce:

    cd "mysqldump --defaults-extra-file=C:\temp\my.cnf --add-drop-table --comments --create-options --dump-date --no-autocommit --routines --set-charset --triggers --result-file=C:\temp" && backup.sql testdatabase

It looks like https://github.com/mikehaertl/php-shellcommand/commit/d9a0e8ecff24badfe07129630a67c3d19e31a094 is really only a fix for absolute paths.

### PR DESCRIPTION
**Pull request by takobell**
Provides several compatibility fixes for Windows and fixes #22.

### CODE REVIEW

File: src/Command.php [hunk 1]
```diff
@@ -147,9 +147,20 @@ public function setCommand($command)
...
+
             // Make sure to switch to correct drive like "E:" first if we have a full path in command
-            $chdrive = (isset($command[1]) && $command[1]===':') ? $command[0].': && ' : '';
-            $command = sprintf($chdrive.'cd %s && %s', escapeshellarg(dirname($command)), basename($command));
+            if (isset($command[1]) && $command[1]===':') {
+                $position = 1;
+                // Could be a quoted absolute path because of spaces. i.e. "C:\Program Files (x86)\file.exe"
+            } elseif (isset($command[2]) && $command[2]===':') {
+                $position = 2;
+            }
```
Comment (takobell) [inline src/Command.php]: No problem and done!
